stages:
  prepare:
    cmd: python src/prepare.py
    deps:
      - src/prepare.py
      - data/data_from_iNaturalist/observations.csv
    params:
      - data.raw_file
      - data.clean_csv
      - data.allowed_species
    outs:
      - data/dataset.csv

  download:
    cmd: python src/download.py
    deps:
      - src/download.py
      - data/dataset.csv
    params:
      - data.clean_csv
      - data.images_dir
    outs:
      - data/dataset_images:
          persist: true 

  train:
    cmd: python src/train.py
    deps:
      - src/train.py
      - data/dataset_images
    params:
      - base.img_size
      - base.random_seed
      - train.batch_size
      - train.epochs
      - train.lr
      - train.model_path
    outs:
      - models/best_model.pth
    plots:
      - results/training_history.json:
          cache: false
          x: epoch
          y: val_acc
          title: Validation Accuracy per Epoch

  evaluate:
    cmd: python src/evaluate.py
    deps:
      - src/evaluate.py
      - models/best_model.pth
      - data/dataset_images
    params:
      - base.img_size
      - base.random_seed
      - train.batch_size
      - train.model_path
    metrics:
      - results/evaluation_metrics.json:
          cache: false
    plots:
      - results/confusion_matrix.png:
          cache: false