base:
  img_size: 224
  embedding_dim: 1280
  random_seed: 42

data:
  raw_file: "data/data_from_iNaturalist/observations.csv"
  clean_csv: "data/dataset.csv"
  images_dir: "data/dataset_images"
  allowed_species:
    - Panthera leo
    - Panthera pardus
    - Panthera onca
    - Panthera tigris
    - Panthera uncia

model:
  weights_path: "model_weights/best_model.pth"

output:
  index_file: "faiss_index/vector_index.bin"
  paths_file: "faiss_index/image_paths.json"